disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - multiple_closures_with_trailing_closure
  - closure_parameter_position
  - function_parameter_count
  - unused_optional_binding
  - cyclomatic_complexity
  - large_tuple
  - function_body_length
  - line_length
  - empty_enum_arguments
line_length:
  - 200 # warning
  - 250 # error
type_body_length:
  - 300 # warning
  - 400 # error
file_length:
  warning: 500
  error: 1200
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods